# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myhello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmyhello.proto\x12\x07myhello\"\x14\n\x04Name\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x14\n\x05Reply\x12\x0b\n\x03msg\x18\x01 \x01(\t2;\n\x0cMyHelloReply\x12+\n\x08GetReply\x12\r.myhello.Name\x1a\x0e.myhello.Reply\"\x00\x62\x06proto3')



_NAME = DESCRIPTOR.message_types_by_name['Name']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), {
  'DESCRIPTOR' : _NAME,
  '__module__' : 'myhello_pb2'
  # @@protoc_insertion_point(class_scope:myhello.Name)
  })
_sym_db.RegisterMessage(Name)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'myhello_pb2'
  # @@protoc_insertion_point(class_scope:myhello.Reply)
  })
_sym_db.RegisterMessage(Reply)

_MYHELLOREPLY = DESCRIPTOR.services_by_name['MyHelloReply']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAME._serialized_start=26
  _NAME._serialized_end=46
  _REPLY._serialized_start=48
  _REPLY._serialized_end=68
  _MYHELLOREPLY._serialized_start=70
  _MYHELLOREPLY._serialized_end=129
# @@protoc_insertion_point(module_scope)
