# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import myhello_pb2 as myhello__pb2


class MyHelloReplyStub(object):
    """提供的服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReply = channel.unary_unary(
                '/myhello.MyHelloReply/GetReply',
                request_serializer=myhello__pb2.Name.SerializeToString,
                response_deserializer=myhello__pb2.Reply.FromString,
                )


class MyHelloReplyServicer(object):
    """提供的服务
    """

    def GetReply(self, request, context):
        """服务端提供的方法，客户端访问的方法
        方法的参数类型，响应类型
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MyHelloReplyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReply': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReply,
                    request_deserializer=myhello__pb2.Name.FromString,
                    response_serializer=myhello__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myhello.MyHelloReply', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MyHelloReply(object):
    """提供的服务
    """

    @staticmethod
    def GetReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myhello.MyHelloReply/GetReply',
            myhello__pb2.Name.SerializeToString,
            myhello__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
