"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class CreateUserRequest(google.protobuf.message.Message):
    """create user"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    USER_NAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    uid: builtins.str
    user_name: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
        user_name: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "uid", b"uid", "user_name", b"user_name"]) -> None: ...

global___CreateUserRequest = CreateUserRequest

@typing_extensions.final
class DeleteUserRequest(google.protobuf.message.Message):
    """delete user"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    uid: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uid", b"uid"]) -> None: ...

global___DeleteUserRequest = DeleteUserRequest

@typing_extensions.final
class LoginUserRequest(google.protobuf.message.Message):
    """login user"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    uid: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["password", b"password", "uid", b"uid"]) -> None: ...

global___LoginUserRequest = LoginUserRequest

@typing_extensions.final
class LoginUserResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    USER_NAME_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    uid: builtins.str
    user_name: builtins.str
    token: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
        user_name: builtins.str = ...,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["token", b"token", "uid", b"uid", "user_name", b"user_name"]) -> None: ...

global___LoginUserResult = LoginUserResult

@typing_extensions.final
class LogoutUserRequest(google.protobuf.message.Message):
    """logout user"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    TOKEN_FIELD_NUMBER: builtins.int
    uid: builtins.str
    token: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["token", b"token", "uid", b"uid"]) -> None: ...

global___LogoutUserRequest = LogoutUserRequest

@typing_extensions.final
class GetUidByTokenRequest(google.protobuf.message.Message):
    """check login"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["token", b"token"]) -> None: ...

global___GetUidByTokenRequest = GetUidByTokenRequest

@typing_extensions.final
class GetUidByTokenResult(google.protobuf.message.Message):
    """check login"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UID_FIELD_NUMBER: builtins.int
    uid: builtins.str
    def __init__(
        self,
        *,
        uid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["uid", b"uid"]) -> None: ...

global___GetUidByTokenResult = GetUidByTokenResult
