name: Compile protobuf

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install protobuf
      run: |
        sudo apt-get install protobuf-compiler
        pip install grpcio grpcio-tools protobuf

    - name: Compile protobuf files to Python
      run: |
        protoc --python_out=${{ github.workspace }}/generated -I=${{ github.workspace }}/movie_proto movie.proto

    -name: Commit files
      uses: EndBug/add-and-commit@v7
        with:
          author_name: aapanhao
          author_email: aapanhao@gmail.com
          message: 'Generated protobuf files'
          add: |
            generated/*.py
          force: true

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}