name: Build Proto

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build protos
      uses: grpc/grpc-gateway@v2.4.0
      with:
        proto_path: ./movie_proto
        plugin: python