name: Compile protobuf

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install protobuf
      run: |
        sudo apt-get install protobuf-compiler
        pip install protobuf

    - name: Compile protobuf files to Python
      run: |
        protoc --python_out=${{ github.workspace }}/movie_proto --grpc_python_out=${{ github.workspace }}/movie_proto -I=${{ github.workspace }}/movie_proto ${GLOB_PATTERN}
      env:
        GLOB_PATTERN: "movie.proto"
